### ISSUE TITLE
installation fails when c extensions unavailable

### ISSUE THREAD

**Issue by michael-basil** [ndparker/rjsmin#7]
Can the setup.py be adjusted to fallback to a python only install?  Similar to how simplejson does it:

https://github.com/simplejson/simplejson/blob/master/setup.py

**Comment by ndparker** [comment]
I think, having a clear error is actually better. You should be able to disable the compilation with the --without-c-extensions argument to setup.py install.

**Comment by mbasil77** [comment]
That solution doesn't work well.  I'm forced to call out the use of rjsmin and rcssmin (instead of respecting the natural dependency chain) because they require special handling.  It makes our Kudo auto deployment scripts brittle and hard (for anyone else in my organization) to maintain.

A reasonable alternate solution would be to provide the wheels if this type of hard error approach is desired.  

Quite frankly, it does not work well on the Azure App Service whereas every other dependency of wagtail / django / django-compressor work fine.  Microsoft is (now) making a concerted effort to support and empower open source initiatives.  Meeting them halfway would seem appropriate.

mb

**Comment by ndparker** [comment]
This has finally been fixed in Release 1.1.0.

**Comment by ant6** [comment]
Thank you very much 😄 !
